name: test-core-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - .github/workflows/faux-crucible-ci.yaml
      - .github/workflows/faux-benchmark-crucible-ci.yaml
      - .github/workflows/faux-core-crucible-ci.yaml
      - .github/workflows/faux-tool-crucible-ci.yaml
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-core-crucible-ci:
    strategy:
      fail-fast: false
      matrix:
        repos:
        - subproject: "rickshaw"
          branch: "master"
        - subproject: "crucible"
          branch: "master"
    uses: ./.github/workflows/core-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.subproject }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}

  test-core-crucible-ci-complete:
    runs-on: ubuntu-latest
    needs: call-core-crucible-ci
    steps:
    - name: Confirm Success
      run: echo "test-core-crucible-ci-complete"
